# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "52939aa6338e7bbed9df9685142635bb"
name = "social-proof-popups"
application_url = "https://social-proof-popup.vercel.app"
embedded = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = [ "app/uninstalled" ]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = [ "app/scopes_update" ]
uri = "/webhooks/app/scopes_update"

[[webhooks.subscriptions]]
topics = [ "orders/create" ]
uri = "/webhooks/orders/create"

[access_scopes]
scopes = "read_themes,read_orders,read_products"

[auth]
redirect_urls = [ "https://social-proof-popup.vercel.app/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""
