# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f113a1dded36139ac4cdc4ad43dbc119"
name = "Trust Badge Builder"
application_url = "https://socailproofpopups.vercel.app"
embedded = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,read_orders,read_products"

[auth]
redirect_urls = [ "https://socailproofpopups.vercel.app/auth/callback" ]

[app_proxy]
url = "https://socailproofpopups.vercel.app"
subpath = "social-proof"
prefix = "/apps"

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""
