# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2f337c3c71eebed6e4fd9549f70c48fb"
name = "socialproof"
application_url = "https://social-proofpopup.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "socialproof-2.myshopify.com"

[webhooks]
api_version = "2025-01"

[[webhooks.subscriptions]]
topics = [ "orders/create" ]
uri = "/webhooks/orders/create"

[access_scopes]
scopes = "read_orders,read_products,read_themes"

[auth]
redirect_urls = [ "https://social-proofpopup.vercel.app/auth/callback" ]
