# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "52939aa6338e7bbed9df9685142635bb"
name = "social-proof-popups"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
